version: "3.7"

services:
    bot:
        image: docker.pkg.github.com/eveisesi/esi-bot-v2/esi-bot:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        command: ./eb2
        container_name: bot
        hostname: bot
        env_file:
            - .env
    ui:
        image: docker.pkg.github.com/eveisesi/tf-slack-invite/tf-slack-invite:0.1.2
        restart: always
        container_name: tf-slack-invite
        hostname: tf-slack-invite
        ports:
            - "5000:80"
