version: "3.7"

services:
    bot:
        image: docker.pkg.github.com/eveisesi/esi-bot-v2/esi-bot:${DOCKER_VERSION}
        restart: on-failure
        container_name: bot
        hostname: bot
        env_file:
            - .env
